#  Please refer to the wiki(https://github.com/nlef/moonraker-telegram-bot/wiki) for detailed information on how to configure the bot

[bot]
server: localhost
bot_token: 7228114669:AAFV5oFe5H1EMZ2xLX_Y8IHTpdx1ut8GPsc
chat_id: 440013288

[camera]
host: http://localhost:8080/?action=stream
type: mjpeg

[progress_notification]
percent: 25
height: 0
time: 0

[timelapse]
cleanup: true
manual_mode: false
